[book]
authors = ["Celestia Labs"]
language = "en"
multilingual = false
src = "src"
title = "go-header Specifications"

[output.html]
git-repository-url = "https://github.com/celestiaorg/go-header"

[rust]
edition = "2021"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
